<?php
if ( function_exists( 'acf_add_local_field_group' ) ):

acf_add_local_field_group( array(
    'key' => 'group_6373638767615',
    'title' => '广告位',
    'fields' => array(
        array(
            'key' => 'field_6385de0251210',
            'label' => '全局广告',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6385de0b51211',
            'label' => '全局广告',
            'name' => 'add_ad_all',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '在此选择您需要的广告类型',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_639822553c59d',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '新建广告组',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_6385de8c51215',
                    'label' => '内容',
                    'name' => 'content',
                    'aria-label' => '',
                    'type' => 'flexible_content',
                    'instructions' => '在此选择您需要的广告类型',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '60',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_6385de9b0cd12' => array(
                            'key' => 'layout_6385de9b0cd12',
                            'name' => 'ad_img',
                            'label' => '图片内容',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_63e2178e29143',
                                    'label' => '广告内容',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_6385deb051216',
                                    'label' => '图片',
                                    'name' => 'img',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_6385debc51217',
                                    'label' => '链接',
                                    'name' => 'link',
                                    'aria-label' => '',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                                array(
                                    'key' => 'field_63e217b829144',
                                    'label' => '配置',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_63e30d57ec6bd',
                                    'label' => '配置',
                                    'name' => 'option',
                                    'aria-label' => '',
                                    'type' => 'group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_63e217c629145',
                                            'label' => '隐藏水印',
                                            'name' => 'watermark',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '默认隐藏水印，水印将显示在图片中的右下角',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui_on_text' => '显示水印',
                                            'ui_off_text' => '隐藏水印',
                                            'ui' => 1,
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_6385def051218' => array(
                            'key' => 'layout_6385def051218',
                            'name' => 'ad_html',
                            'label' => 'HTML内容',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6385def851219',
                                    'label' => 'HTML',
                                    'name' => 'content',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 1,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_6385e185b0fc3' => array(
                            'key' => 'layout_6385e185b0fc3',
                            'name' => 'ad_carousel',
                            'label' => '轮播图内容',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_639c19d6607bd',
                                    'label' => '幻灯片',
                                    'name' => 'box',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => 'field_639c1ac315c4d',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '添加新幻灯',
                                    'rows_per_page' => 20,
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_639c1ac315c4d',
                                            'label' => '图片',
                                            'name' => 'img',
                                            'aria-label' => '',
                                            'type' => 'image',
                                            'instructions' => '幻灯展示用的图片',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                            'parent_repeater' => 'field_639c19d6607bd',
                                        ),
                                        array(
                                            'key' => 'field_639c1aab15c4c',
                                            'label' => '链接',
                                            'name' => 'link',
                                            'aria-label' => '',
                                            'type' => 'link',
                                            'instructions' => '点击幻灯片打开的链接',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'parent_repeater' => 'field_639c19d6607bd',
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_63d644594ba6c' => array(
                            'key' => 'layout_63d644594ba6c',
                            'name' => 'ad_test',
                            'label' => '测试内容',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_63d6469cc239a',
                                    'label' => '内容',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_63d6446c4ba6d',
                                    'label' => '详细选项',
                                    'name' => '详细选项',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'basic',
                                    'media_upload' => 1,
                                    'delay' => 1,
                                ),
                                array(
                                    'key' => 'field_63d6477f8ffc2',
                                    'label' => '配置',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_63d647918ffc3',
                                    'label' => '是否悬浮',
                                    'name' => '是否悬浮',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '在有些位置可能不起作用',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '悬浮显示广告',
                                    'default_value' => 0,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                array(
                                    'key' => 'field_63d647d18ffc4',
                                    'label' => '位置',
                                    'name' => '位置',
                                    'aria-label' => '',
                                    'type' => 'button_group',
                                    'instructions' => '默认为顶部',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        '0:默认' => '0:默认',
                                        '1:顶部' => '1:顶部',
                                        '2:底部' => '2:底部',
                                    ),
                                    'allow_null' => 0,
                                    'default_value' => '',
                                    'layout' => 'horizontal',
                                    'return_format' => 'value',
                                ),
                                array(
                                    'key' => 'field_63d648178ffc5',
                                    'label' => '距离',
                                    'name' => '距离',
                                    'aria-label' => '',
                                    'type' => 'range',
                                    'instructions' => '距离顶部或底部的距离，单位为px',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'min' => '',
                                    'max' => '',
                                    'step' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_63e34f77e4485' => array(
                            'key' => 'layout_63e34f77e4485',
                            'name' => 'ad_out_bounds',
                            'label' => '界外广告',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_63e35027e4489',
                                    'label' => '内容',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_63e34fd2e4487',
                                    'label' => '左边',
                                    'name' => 'lift_editor',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'default_value' => '',
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_63e34ff8e4488',
                                    'label' => '右边',
                                    'name' => 'right_editor',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'default_value' => '',
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_63e3503be448a',
                                    'label' => '配置',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_63e35046e448b',
                                    'label' => '距离',
                                    'name' => 'distance',
                                    'aria-label' => '',
                                    'type' => 'range',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'min' => '',
                                    'max' => '',
                                    'step' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                    'button_label' => '添加广告',
                    'parent_repeater' => 'field_6385de0b51211',
                ),
                array(
                    'key' => 'field_639822553c59d',
                    'label' => '配置',
                    'name' => 'options',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '对于广告组的显示类型配置',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6385de2151212',
                            'label' => '是否展示',
                            'name' => 'judge',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '默认',
                                1 => '随机',
                                2 => '隐藏',
                            ),
                            'default_value' => 0,
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'layout' => 'horizontal',
                        ),
                        array(
                            'key' => 'field_63e2fc02593a7',
                            'label' => '登录展示',
                            'name' => 'sign',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '默认',
                                1 => '仅登录',
                                2 => '仅非登录',
                            ),
                            'default_value' => 0,
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'layout' => 'horizontal',
                        ),
                        array(
                            'key' => 'field_6385de5551213',
                            'label' => '展示平台',
                            'name' => 'platform',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '默认',
                                1 => '仅手机',
                                2 => '仅电脑',
                            ),
                            'default_value' => 0,
                            'return_format' => 'value',
                            'allow_null' => 0,
                            'layout' => 'horizontal',
                        ),
                        array(
                            'key' => 'field_6385de6d51214',
                            'label' => '展示位置',
                            'name' => 'position',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '默认',
                                1 => '文章内容顶部',
                                2 => '文章内容底部',
                                3 => '文章内容第三段',
                                4 => '全站顶部',
                                5 => '全站底部',
                                6 => '仅文章页顶部',
                                7 => '仅文章页底部',
                                8 => '仅首页顶部',
                                9 => '仅首页底部',
                                10 => '仅分类页顶部',
                                11 => '仅分类页底部',
                                12 => '仅标签页顶部',
                                13 => '仅标签页底部',
                                14 => '仅单页顶部',
                                15 => '仅单页底部',
                                16 => '仅搜索结果页顶部',
                                17 => '仅搜索结果页底部',
                                18 => '仅404页顶部',
                                19 => '仅404页底部',
                                20 => '仅作者页顶部',
                                21 => '仅作者页底部',
                            ),
                            'default_value' => 0,
                            'return_format' => 'value',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                    'parent_repeater' => 'field_6385de0b51211',
                ),
            ),
        ),
        array(
            'key' => 'field_6392f4b78f5a2',
            'label' => '指定广告',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6392f441d86e3',
            'label' => '指定广告',
            'name' => 'add_ad_appoint',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_6392fbe59ffd2',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '添加新广告',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_6392f441d86e4',
                    'label' => '内容',
                    'name' => 'content',
                    'aria-label' => '',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_6385de9b0cd12' => array(
                            'key' => 'layout_6385de9b0cd12',
                            'name' => 'ad_img',
                            'label' => '图片内容',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6392f441d86e5',
                                    'label' => '图片',
                                    'name' => 'img',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_6392f441d86e6',
                                    'label' => '链接',
                                    'name' => 'link',
                                    'aria-label' => '',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_6385def051218' => array(
                            'key' => 'layout_6385def051218',
                            'name' => 'ad_html',
                            'label' => 'HTML内容',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6392f441d86e7',
                                    'label' => 'HTML',
                                    'name' => 'content',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 1,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_63a0287d701af' => array(
                            'key' => 'layout_63a0287d701af',
                            'name' => 'ad_carousel',
                            'label' => '轮播图',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_63a02888701b0',
                                    'label' => '',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'clone',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'clone' => array(
                                        0 => 'field_639c19d6607bd',
                                    ),
                                    'display' => 'seamless',
                                    'layout' => 'block',
                                    'prefix_label' => 0,
                                    'prefix_name' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => '添加模块',
                    'min' => '',
                    'max' => '',
                    'parent_repeater' => 'field_6392f441d86e3',
                ),
                array(
                    'key' => 'field_6392fbe59ffd2',
                    'label' => '配置',
                    'name' => 'options',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '0',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6392f463d86f7',
                            'label' => '指定文章',
                            'name' => 'location',
                            'aria-label' => '',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'post',
                            ),
                            'taxonomy' => '',
                            'allow_null' => 0,
                            'multiple' => 1,
                            'return_format' => 'id',
                            'ui' => 1,
                        ),
                        array(
                            'key' => 'field_6392f441d86f4',
                            'label' => '是否显示',
                            'name' => 'judge',
                            'aria-label' => '',
                            'type' => 'button_group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '隐藏',
                                1 => '展示',
                                2 => '随机',
                            ),
                            'allow_null' => 0,
                            'default_value' => 1,
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        array(
                            'key' => 'field_6392f441d86f5',
                            'label' => '显示平台',
                            'name' => 'platform',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '全平台',
                                1 => '仅电脑端',
                                2 => '仅手机端',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6392f441d86f6',
                            'label' => '显示位置',
                            'name' => 'position',
                            'aria-label' => '',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '默认',
                                1 => '文章内容顶部',
                                2 => '文章内容底部',
                                3 => '文章内容第三段',
                                4 => '仅文章顶部',
                                5 => '仅文章底部',
                            ),
                            'default_value' => false,
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                    'parent_repeater' => 'field_6392f441d86e3',
                ),
            ),
        ),
        array(
            'key' => 'field_63787c457b45b',
            'label' => '其他广告',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_6377620532919',
            'label' => '添加弹窗广告',
            'name' => 'ad_notification',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '弹窗广告配置',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_63787bfac1dc9',
                    'label' => '开关',
                    'name' => 'ad_notification_switch',
                    'aria-label' => '',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        0 => '关闭弹窗',
                        1 => '简洁样式弹窗',
                        2 => '谷歌样式弹窗',
                    ),
                    'allow_null' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_63787c8fb7c39',
                    'label' => '弹出周期？',
                    'name' => 'ad_notification_cycle',
                    'aria-label' => '',
                    'type' => 'range',
                    'instructions' => '默认1天弹出一次',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '!=',
                                'value' => '0',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'min' => 1,
                    'max' => 365,
                    'step' => '',
                    'prepend' => '',
                    'append' => '天',
                ),
                array(
                    'key' => 'field_63848b629b9fb',
                    'label' => '谷歌广告-打开按钮',
                    'name' => 'ad_notification_button-link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '==',
                                'value' => '2',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                ),
                array(
                    'key' => 'field_63849ed007a1a',
                    'label' => '谷歌广告-打开按钮文本',
                    'name' => 'ad_notification_button-text',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '按钮文本',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '==',
                                'value' => '2',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '打开',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_63848ba09b9fc',
                    'label' => '谷歌广告-品牌LOGO',
                    'name' => 'ad_notification_logo',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '推荐尺寸：1200X300',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '==',
                                'value' => '2',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_63787cd5b7c3a',
                    'label' => '弹窗标题',
                    'name' => 'ad_notification_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '不填则不显示标题',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '!=',
                                'value' => '0',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_63787cf2b7c3b',
                    'label' => '弹窗内容',
                    'name' => 'ad_notification_content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '纯图片建议比例：4:3',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '!=',
                                'value' => '0',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 1,
                ),
                array(
                    'key' => 'field_6378aa4aafc4c',
                    'label' => '调试按钮',
                    'name' => 'ad_notification_debug',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '在页面底部添加一个展示弹窗的按钮，点击即可查看弹窗效果',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63787bfac1dc9',
                                'operator' => '!=',
                                'value' => '0',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '启用',
                    'ui_off_text' => '关闭',
                ),
            ),
        ),
        array(
            'key' => 'field_63e37182292db',
            'label' => '两侧广告',
            'name' => 'ad_both_sides',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_63e371b0e7d7c',
                    'label' => '是否启用',
                    'name' => 'both_sides_hide',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui_on_text' => '启用',
                    'ui_off_text' => '禁用',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_63e371c1e7d7d',
                    'label' => '左内容',
                    'name' => 'left',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '推荐图片尺寸：180X500，用span标签包裹广告，可启用默认样式',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63e371b0e7d7c',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 1,
                ),
                array(
                    'key' => 'field_63e371cee7d7e',
                    'label' => '右内容',
                    'name' => 'right',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '推荐图片尺寸：180X500，用span标签包裹广告，可启用默认样式',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63e371b0e7d7c',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 1,
                ),
                array(
                    'key' => 'field_63e371dbe7d7f',
                    'label' => '两边距离',
                    'name' => 'sides',
                    'aria-label' => '',
                    'type' => 'range',
                    'instructions' => '广告距离两端推荐100px',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63e371b0e7d7c',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 100,
                    'min' => 0,
                    'max' => 1000,
                    'step' => '',
                    'prepend' => '',
                    'append' => 'px',
                ),
                array(
                    'key' => 'field_63e371f0e7d80',
                    'label' => '顶部距离',
                    'name' => 'top',
                    'aria-label' => '',
                    'type' => 'range',
                    'instructions' => '广告距离顶部，推荐300px',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_63e371b0e7d7c',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 300,
                    'min' => 0,
                    'max' => 1000,
                    'step' => '',
                    'prepend' => '',
                    'append' => 'px',
                ),
            ),
        ),
        array(
            'key' => 'field_63dc62c06f8d4',
            'label' => '高级广告（调试中）',
            'name' => 'asdfsadf',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_63784ea0bda63',
                    'label' => '专业元素添加（开发中）',
                    'name' => 'repeater_element',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '专业人士使用，很强大的自定义添加',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '添加行',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_63784fb9bda67',
                            'label' => '添加的内容',
                            'name' => 'element_content',
                            'aria-label' => '',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                            'parent_repeater' => 'field_63784ea0bda63',
                        ),
                        array(
                            'key' => 'field_63784f1dbda64',
                            'label' => '修改的页面',
                            'name' => 'element_page',
                            'aria-label' => '',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                0 => '首页',
                                1 => '文章页',
                                2 => '单页',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => '',
                            'layout' => 'vertical',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                            'parent_repeater' => 'field_63784ea0bda63',
                        ),
                        array(
                            'key' => 'field_63784f7abda65',
                            'label' => '目标ID元素',
                            'name' => 'element_id',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '离目标最近的ID元素',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_63784ea0bda63',
                        ),
                        array(
                            'key' => 'field_63784fa1bda66',
                            'label' => '离目标最近的class',
                            'name' => 'element_class',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_63784ea0bda63',
                        ),
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_63dc5e8a13f29',
            'label' => '设置',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_63e34dc5be713',
            'label' => '隐藏字段',
            'name' => 'acf_hide',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '显示字段',
            'ui_off_text' => '隐藏字段',
            'ui' => 1,
        ),
        array(
            'key' => 'field_63856f5ccbb8d',
            'label' => '选项卡（测试中）',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_63dc621fab631',
            'label' => '测试下字段',
            'name' => '测试下字段',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_6392fe18eee8c',
                    'label' => '大段内容',
                    'name' => '大段内容',
                    'aria-label' => '',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_6392fe21508ba' => array(
                            'key' => 'layout_6392fe21508ba',
                            'name' => '',
                            'label' => '',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6392fe29eee8d',
                                    'label' => '阿斯顿发斯蒂芬',
                                    'name' => '阿斯顿发斯蒂芬',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_6392fe31eee8e',
                                    'label' => '阿斯顿发斯蒂芬阿斯蒂芬阿斯蒂芬',
                                    'name' => '阿斯顿发斯蒂芬阿斯蒂芬阿斯蒂芬',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => '添加行',
                    'min' => '',
                    'max' => '',
                ),
                array(
                    'key' => 'field_639824e6b2251',
                    'label' => 'img',
                    'name' => 'img',
                    'aria-label' => '',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'red' => '<img decoding="async" alt="222" class="syl-page-img" src="http://kdx.mqzj.top/wp-content/uploads/2022/12/plain.png">',
                        'res' => '<img decoding="async" alt="222" class="syl-page-img" src="http://kdx.mqzj.top/wp-content/uploads/2022/12/plain.png">',
                    ),
                    'allow_null' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                array(
                    'key' => 'field_63dc5ff562e65',
                    'label' => '简单分组',
                    'name' => '水电费撒打发斯蒂芬',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_63e2fbb846fe3',
                            'label' => '1',
                            'name' => '11',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_63e2fbbf46fe4',
                            'label' => '2',
                            'name' => '22',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_63dc65940f5f0',
                    'label' => '消息',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<div class="user-data">
				<div class="data-item">
						<div class="icon" style="background-image:url(https://p5.ssl.qhimg.com/t01bda78253a6640398.png)"></div>
						<div class="right">
								<div class="amount"><span class="num">100</span>万</div>
								<div class="desc">注册客户数</div>
						</div>
				</div>
				<div class="data-item">
						<div class="icon" style="background-image:url(https://p4.ssl.qhimg.com/t010319dab6802cfbfe.png)"></div>
						<div class="right">
								<div class="amount"><span class="num">1500</span>万</div>
								<div class="desc">最高同时在线人数</div>
						</div>
				</div>
				<div class="data-item">
						<div class="icon" style="background-image:url(https://p1.ssl.qhimg.com/t01f9fbff16eb500869.png)"></div>
						<div class="right">
								<div class="amount"><span class="num">2000</span>万</div>
								<div class="desc">终端用户数</div>
						</div>
				</div>
		</div>
		<style>
				.user-data {
						position: absolute;
						left: 50%;
						transform: translate(-50%, -50%);
						display: flex;
						align-items: center;
						justify-content: center;
						width: 1200px;
						height: 100px;
						border: 1px solid #fff;
						border-radius: 8px;
						background: linear-gradient(180deg, #f4f5f8 4%, hsla(0, 0%, 100%, .7));
						box-shadow: -4px 0 8px 0 rgb(37 56 108 / 5%), 0 2px 6px 0 rgb(37 56 108 / 15%), 0 10px 20px 0 rgb(49 70 125 / 10%);
						-webkit-backdrop-filter: blur(27px);
						backdrop-filter: blur(27px);
						z-index: 20;
				}

				.data-item {
						width: 33.33333%;
						height: 66px;
						position: relative;
						display: flex;
						align-items: center;
				}

				.icon {
						margin-left: 105px;
						width: 70px;
						height: 70px;
						background-size: cover;
						background-repeat: no-repeat;
				}

				.right {
						margin-left: 16px;
						font-size: 14px;
						color: #191919;
				}

				.amount {
						height: 44px;
						line-height: 44px;
				}

				.num {
						font-family: PingFangSC-Medium;
						color: #0256ff;
						font-size: 36px;
				}

				.desc {
						height: 22px;
						line-height: 22px;
				}

				.user-data .data-item:after {
						position: absolute;
						right: 0;
						content: "";
						width: 2px;
						height: 48px;
						background-image: linear-gradient(90deg, #fff 0, #fff 50%, #dedede 0, #dedede);
				}

				.user-data {
						margin-top: 8em;
				}
		</style>',
                    'new_lines' => '',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_63e2fb782639a',
                    'label' => '重复器',
                    'name' => '重复器',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => '添加行',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_63e2fb852639b',
                            'label' => '1',
                            'name' => '11',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_63e2fb782639a',
                        ),
                        array(
                            'key' => 'field_63e2fb8e2639c',
                            'label' => '2',
                            'name' => '22',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_63e2fb782639a',
                        ),
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'theme-general-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '简简单单的描述',
    'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
    'key' => 'group_639143edab25d',
    'title' => '发文统计',
    'fields' => array(
        array(
            'key' => 'field_6391442a77db4',
            'label' => '人员',
            'name' => 'user',
            'aria-label' => '',
            'type' => 'user',
            'instructions' => '需要统计的人员',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'role' => array(
                0 => 'administrator',
                1 => 'author',
                2 => 'editor',
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'array',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'theme-general-settings',
            ),
        ),
    ),
    'menu_order' => 9,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
) );

endif;
